### ISSUE TITLE
Evilcraft enhanced compatibility request

### ISSUE THREAD

**Issue by ActualAsteroid** [Minecraft-Celestial/CelestialArtifacts#2]
Mods: Evilcraft, Celestial Artifacts

Once you activate Desire on the Catastrophe Scroll, neutral mobs begin to attack you. Normally not an issue and a fun challenge, but with Evilcraft installed killing mobs has a chance to spawn neutral invisible entitites called vengeance spirits. The vengeance spirits are normally only hostile and interactable when you have the vengeance ring, vengeance focus, or spectral glasses equipped. They are quite a pain to deal with when they ignore the design of the mod they are from and attack you regardless.

Having some sort of blacklist for entities that are not affected by desire would be greatly appreciated.

![image](https://github.com/Minecraft-Celestial/CelestialArtifacts/assets/128436839/3950eed6-29a2-47c7-81d7-35f8491ce02a)

**Comment by lcy0x1** [comment]
completed in 1.4.5
